### ISSUE TITLE
Missing manifests/netcat-svc.yaml 

### ISSUE THREAD

**Issue by sadlil** [tstromberg/time-to-k8s#1]
In line https://github.com/tstromberg/time-to-k8s/blob/master/time-to-k8s.go#L185 it seems like there should be a manifests/netcat-svc.yaml file in the directory. Is it missing or something a user needs to configure?

**Comment by StevenACoffman** [comment]
Same.

**Comment by StevenACoffman** [comment]
![local-kubernetes](https://user-images.githubusercontent.com/1942608/117693087-a44cd000-b18b-11eb-82f8-d4d023146a69.png)
Added manifest, and got this on my local mac using minikube with docker driver.

**Comment by tstromberg** [comment]
Fixed by c0a6528
